### ISSUE TITLE
Blank page when typing dot(.) then follows a digit in stake amount input

### ISSUE THREAD

**Issue by knd** [WeTrustPlatform/staking-dapp#26]
![image](https://user-images.githubusercontent.com/1356620/55888398-7a560780-5bd9-11e9-999c-9ce7994e03e0.png)

![image](https://user-images.githubusercontent.com/1356620/55888241-3cf17a00-5bd9-11e9-8ca4-fc79f4043071.png)

**Comment by benminhle** [comment]
Entering in a decimal number (e.g 100.5) will cause the page to go blank
