### ISSUE TITLE
Staking page is scrolling very slow on iOS devices

### ISSUE THREAD

**Issue by knd** [WeTrustPlatform/staking-dapp#36]
On iOS mobile devices, staking.wetrust.io webpage scrolling is very slow. Is there a way to fix it so it is more smooth?

Issue reported by a user on Telegram.

from: https://github.com/WeTrustPlatform/move-ethereum-forward/issues/750

**Comment by sihoang** [comment]
fixed https://github.com/WeTrustPlatform/staking-dapp/commit/ef0e436810704b21f08c654c5f72719a5befd1ff
