### ISSUE TITLE
Implement the Support section

### ISSUE THREAD

**Issue by sihoang** [WeTrustPlatform/staking-dapp#4]
Design https://app.zeplin.io/project/5c7d4755310547bc7e27d82e/screen/5c7d47c1a481f9bcdf72dfbc

- [ ] Content
- [ ] Button: Email to? Subject?

**Comment by gliinbox** [comment]
I don't think a support section is needed? Perhaps we have a question in FAQ that says "need more help?" answer would be "post a question on reddit or contact us on Telegram"

**Comment by sihoang** [comment]
sounds good.  @NancyWeTrust please modify the design.
