### ISSUE TITLE
Add user agreements and privacy policy

### ISSUE THREAD

**Issue by sihoang** [WeTrustPlatform/staking-dapp#7]
I think we can combine the two in one doc

- [ ] Text in Markdown format would be great. PDF is okay.

**Comment by sihoang** [comment]
@gliinbox @benminhle any updates on this?

**Comment by benminhle** [comment]
https://docs.google.com/document/d/1-DeXG6O0t4pqjN8HQ49Mq8HpUr9TqJ966GEaeei9c2w/edit#heading=h.yjg211l4hjwh

**Comment by benminhle** [comment]
For privacy policy,  i believe that we can use the original privacy policy (for Spring) as we don't intend to use any data for different reasons in regards to staking.

**Comment by gliinbox** [comment]
Hey Hoang this is latest draft I will try to finalize tomorrow

**Comment by sihoang** [comment]
@gliinbox is the latest draft ready to go?

**Comment by gliinbox** [comment]
Pat and I have reviewed and here is the final and ready to use:

https://docs.google.com/document/d/1clKYsepGo1zNSHQ_sw4vXv2CGBmGYJLZtZYHKCTBwj8/edit#
